parameters:
#    proyecto.example.class: Sgpg\ProyectoBundle\Example

services:
#    proyecto.example:
#        class: %proyecto.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
