security:

    firewalls:
        #firewall de la parte de administracion o backend
        backend:
            pattern:        ^/backend
            provider:       administradores
            anonymous:      ~
            form_login:
                login_path: /backend/login
                check_path: /backend/login_check
            logout:
                path:       /backend/logout
                target:     /


        #firewall de los estudiantes
        estudiante:
            pattern:        ^/estudiante
            provider:       estudiantes
            anonymous:      ~
            form_login:
                login_path: /estudiante/login
                check_path: /estudiante/login_check
            logout:
                path:       /estudiante/logout
                target:     /

        #firewall de los docentes
        docente:
            pattern:        ^/docente
            provider:       docentes
            anonymous:      ~
            form_login:
                login_path: /docente/login
                check_path: /docente/login_check
            logout:
                path:       /docente/logout
                target:     /

    access_control:
        - { path: ^/estudiante/login,   roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/estudiante/*,       roles: ROLE_ESTUDIANTE}
        - { path: ^/docente/login,      roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/docente/*,          roles: ROLE_DOCENTE }
        - { path: ^/backend/login,      roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/backend/*,          roles: ROLE_ADMIN }

    encoders:
        Sgpg\EstudianteBundle\Entity\Estudiante:     { algorithm: sha512, iterations: 10 }
        Sgpg\DocenteBundle\Entity\Docente:           { algorithm: sha512, iterations: 10 }
        Sgpg\BackendBundle\Entity\Usuario:           { algorithm: sha512, iterations: 10 }
        Symfony\Component\Security\Core\User\User:      sha512

    providers:
        administradores:
            entity: { class: Sgpg\BackendBundle\Entity\Usuario, property: username }

        estudiantes:
            entity: { class: Sgpg\EstudianteBundle\Entity\Estudiante, property: ci }

        docentes:
            entity: { class: Sgpg\DocenteBundle\Entity\Docente, property: ci}

    role_hierarchy:
        ROLE_ADMIN: [ROLE_ESTUDIANTE, ROLE_DOCENTE, ROLE_ALLOWED_TO_SWITCH]