parameters:
#    carrera.example.class: Sgpg\CarreraBundle\Example

services:
#    carrera.example:
#        class: %carrera.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
